processor:
  build: .
  links:
    - rabbitmq
    - db
  env_file: .env
rabbitmq:
  image: rabbitmq:3.5.3-management
  ports:
    - "15672"
  hostname: qa-engine-rabbit
db:
  image: postgres:9.4.1
  ports:
    - "5432"
  environment:
    POSTGRES_USER: dataprocessor
    POSTGRES_PASSWORD: vip2016
